### ISSUE TITLE
can you add linenumbers show?thanks!

### ISSUE THREAD

**Issue by rdaim** [justcaliturner/simple-code-editor#10]
can you add linenumbers show? thanks!

**Comment by justcaliturner** [comment]
@rdaim  It's a good idea, and I'll keep that in mind, thanks for your advice。

**Comment by rdaim** [comment]
nice!!!

**Comment by WilliamFalci** [comment]
#22 I did it for you guys <3

@justcaliturner @rdaim

**Comment by ErwinAI** [comment]
@WilliamFalci Nice! I need this as well. Pull request looks good to me 👍 @justcaliturner Is a new minor version with this pull request possible?

**Comment by WilliamFalci** [comment]
> @WilliamFalci Nice! I need this as well. Added some comments to the pull request 👍 @justcaliturner Is a new minor version with this pull request possible?

Yeah I saw, I answered as well with an +1 commit 😊

**Comment by justcaliturner** [comment]
![1](https://github.com/justcaliturner/simple-code-editor/assets/14209466/6e768728-948d-4f5c-b6d0-2e8fb9fbf97f)

**The new feature "line numbers" has been added**
