### ISSUE TITLE
how to disable the auto corrector? it keeps red-underlying my code snippets

### ISSUE THREAD

**Issue by adnane-ka** [justcaliturner/simple-code-editor#16]
here is a picture that describes the problem
![screenshot-2022-06-12-22-58-51](https://user-images.githubusercontent.com/74255401/173253390-649a2d3c-b1ee-45ff-8b25-6ebc958ebb48.png)

**Comment by justcaliturner** [comment]
@adnane-ka This is a default setting of the browser, you can turn it off like this:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/14209466/173998442-68fb6272-7d27-44e8-a480-1b64e3288c15.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/14209466/173998484-a811a1b3-8fe2-44b0-acb0-ab13dc7964f1.png">
