### ISSUE TITLE
copy is no work

### ISSUE THREAD

**Issue by Yoki-Hua** [justcaliturner/simple-code-editor#18]
Hello! Clipboard （copy code）doesnt work on Chrome 103.0.5060.53
but firefox is work

firefox：
![image](https://user-images.githubusercontent.com/55202023/175352544-bd839126-792a-4cd4-9938-835103792904.png)

my code 
![image](https://user-images.githubusercontent.com/55202023/175352755-c6b23c36-78b1-4f0b-ab4b-e12515ff4421.png)

PS: I have a Q，Can this editor be embedded in a quill ?
![image](https://user-images.githubusercontent.com/55202023/175353396-9fa10399-c31f-46b4-9147-a89c9be43961.png)

**Comment by justcaliturner** [comment]
The package has been updated to version 2.0 (just support for vue 3), please update and try it again.
