### ISSUE TITLE
the cursor is always above the code text

### ISSUE THREAD

**Issue by superoo1** [justcaliturner/simple-code-editor#19]
<img width="775" alt="image" src="https://user-images.githubusercontent.com/29897282/185284336-2851c0ee-b2d0-4d00-82e2-fdbdd23f9151.png">

**Comment by muzaffersenkal** [comment]
Same issue for me, any update ?

**Comment by viperasi** [comment]
find the file "CodeEditor.vue" in "node_modules/simple-code-editor", and find line 59, add style: `style="margin-top: 20px;`, it's a temporary solutions.

**Comment by J3K** [comment]
any update ?

**Comment by justcaliturner** [comment]
Package has updated to 2.0, please try it again.
