### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Xeyos88** [justcaliturner/simple-code-editor#20]
Hi,
i have this error using this package:
`SyntaxError: The requested module '/node_modules/highlight.js/lib/index.js?v=a76deadf' does not provide an export named 'default' (at index.js?v=a76deadf:2:8)
`
I use vite.
I have currently removed lang = "ts" from my script (I saw it doesn't support it).
I imported the component in a simple way:
```javascript
import CodeEditor from 'simple-code-editor'
```

**Comment by martinszeltins** [comment]
I am getting the same error.

**Comment by cooljet84** [comment]
I've solved this by installing highlight.js:

 npm install highlight.js

Also using Vite

**Comment by nosehair** [comment]
@cooljet84  - can't get it working as per your suggestion. also using vite

**Comment by nayan-7span** [comment]
> I've solved this by installing highlight.js:
> 
> npm install highlight.js and importing hljs
> 
> ```js
> import hljs from "highlight.js";
> import CodeEditor from 'simple-code-editor'
> ```
> 
> Also using Vite

Thank You! It is working perfectly.

**Comment by Niush** [comment]
Instead of importing `hightlight.js` everywhere and potentially getting eslint's unused vars warning. We can add this to `vite.config.js` file:

```js
// ...
optimizeDeps: {
    include: ['highlight.js']
}
```
