### ISSUE TITLE
Input is not transferred from textarea to the code element

### ISSUE THREAD

**Issue by Brambo27** [justcaliturner/simple-code-editor#3]
Hi I'm trying to use this in my Nuxt project I imported it as a plugin and everything seemed to work except when I type anything in the code editor it doesn't get displayed. The text cursor does move and when I initialize the v-model with some text that does get displayed.

```
<template>
<div>
  <CodeEditor width="100%" height="100%" :languages="[['html', 'HTML']]" v-model="content"></CodeEditor>
</div>
</template>

<script lang="ts">

import { Component, Vue } from 'nuxt-property-decorator';
import CodeEditor from '~/plugins/simple-code-editor.js'

@Component({
  components: {
    CodeEditor,
  },
})
export default class Index extends Vue {
  public content: string = '<div></div>';
}
</script>
```

contents of `'~/plugins/simple-code-editor.js'`

```
import Vue from 'vue'
import CodeEditor from 'simple-code-editor'

Vue.use(CodeEditor)
export default CodeEditor
```

Am I missing something? Thanks in advance.

**Comment by justcaliturner** [comment]
If the code can not be displayed while typing but it can be displayed with initialized data values, the problem should be the data synchronization between textarea and highlight renderer, I saw your script language is Typescript, this editor is not supported for ts now，so you can try again in Javascript

**Comment by justcaliturner** [comment]
@Brambo27 If the code can not be displayed while typing but it can be displayed with initialized data values, the problem should be the data synchronization between textarea and highlight renderer, I saw your script language is Typescript, this editor is not supported for ts now，so you can try again in Javascript

**Comment by Brambo27** [comment]
Ah thanks that makes sense, I'll try that.

**Comment by cyberz** [comment]
Same issue on Nuxt JS v2, v-model not working
