### ISSUE TITLE
SyntaxError: indirect export not found: HighlightJS

### ISSUE THREAD

**Issue by markteekman** [justcaliturner/simple-code-editor#4]
First of, I love this component! It looks and works really nice 🙂 Since we went from the Vue-CLI to Vite I'm getting an error when I use this component however. This logs to the console:

![screenshot](https://user-images.githubusercontent.com/3909046/151998632-2d604488-b742-4081-a271-5e8e6ec55dc2.png)

When I click on the second error I get the following statement:

![screenshot(1)](https://user-images.githubusercontent.com/3909046/151998895-cce326e1-f49c-4428-bf38-feb83847c70b.png)

I tried testing it with a custom component and it seems to work when you upgrade the hightlight.js package to the latest version.

**Comment by gfrison** [comment]
hello. how can I fix it? thank you

**Comment by markteekman** [comment]
@gfrison it should be fixed by changing this in your `package.json`:

```json
"dependencies": {
  "highlight.js": "^11.3.1"
}
```

To this:

```json
"dependencies": {
  "highlight.js": "^11.4.0"
}
```

**Comment by justcaliturner** [comment]
@gfrison @markteekman 

In Vite, it needs to import the `hljs`  before the `CodeEditor` component, like this:
```
 import hljs from "highlight.js";
 import CodeEditor from 'simple-code-editor';
```

**Comment by markteekman** [comment]
Thanks for the update @justcaliturner, that should work! 😊

**Comment by cyrilf** [comment]
As mentioned by [@niushSitaula](https://github.com/Niush) in https://github.com/justcaliturner/simple-code-editor/issues/20#issuecomment-1607965425, I've solved it by doing:
```
export default defineConfig({
  plugins: [vue()],
  ...,
  optimizeDeps: {
    include: ["highlight.js"],
  },
});

```
