### ISSUE TITLE
Clipboard Safari problem

### ISSUE THREAD

**Issue by Shooosty** [justcaliturner/simple-code-editor#6]
Hello! Clipboard doesnt  work on Safari browser. Pls pay attention to this problem

**Comment by justcaliturner** [comment]
Do you mean the "copy code" feature? It looks worked in my Safari browser, and which version of Safari do you use?

**Comment by justcaliturner** [comment]
@Shooosty The Clipboard bug on the Safari browser has been fixed, you can try to update the npm package, thanks

**Comment by nickfrosty** [comment]
The clipboard copy is not working in Chrome based browsers (including Chrome, Edge, and Brave)
I will submit a PR shortly with recommended changes :)

**Comment by justcaliturner** [comment]
@nickfrosty Awesome! Thanks for your contribution.

**Comment by nickfrosty** [comment]
@justcaliturner no problem!
