### ISSUE TITLE
Nuxt.js usage

### ISSUE THREAD

**Issue by phazonoverload** [justcaliturner/simple-code-editor#7]
Hey! 

Firstly, thanks so much for this library. If it works once I get it set up it looks like an excellent and straightforward way to include code editors. 

I'm struggling to get this set up with Nuxt. I have installed the npm package, imported and registered it:

```html
<script>
import CodeEditor from 'simple-code-editor'

export default {
    components: {
        CodeEditor
    }
}
</script>
```

And used it as per the docs:

```html
<CodeEditor value="console.log(13)" />
```

When I load the page, I get an error:

<img width="837" alt="image" src="https://user-images.githubusercontent.com/1461554/161387082-78cca529-554e-47c0-9cf5-ea7f2de52c7b.png">

Any suggestions would be super welcome. Cheers!

**Comment by justcaliturner** [comment]
Thanks for your feedback, this is a problem with the path of the node_module, and the fastest way to solve it is: 
`import CodeEditor from "../node_modules/simple-code-editor";`
By the way, this component needs to be used on the `Vue 3`.

**Comment by phazonoverload** [comment]
Updating the import path fixed the issue, thank you!
