### ISSUE TITLE
Hello! Clipboard doesnt work on Chrome browser. Pls pay attention to this problem too

### ISSUE THREAD

**Issue by rdaim** [justcaliturner/simple-code-editor#8]
Hello! Clipboard doesnt work on Chrome browser. Pls pay attention to this problem,too
my chrome ver is : 版本 100.0.4896.75（正式版本） (x86_64)
firefox is working

**Comment by rdaim** [comment]
and , I fixed it with:
      var userAgent = navigator.userAgent; //
      if (userAgent.indexOf("Chrome") > -1){
        let value = this.$refs.textarea.value;
        navigator.clipboard.writeText(value);        
      }else{
        this.$refs.textarea.select();
        document.execCommand("copy");        
      }

thanks.

**Comment by justcaliturner** [comment]
@rdaim  Thanks, I have added the `Clipboard` API for the browsers which do not support `document.execCommand()`.
You can try to update the npm package, thanks again.
